name: Home Management
version: 1.0
slug: home_management
description: Configures desktop and Home Assistant interface on HDMI
maintainer: Erik Cokeley
arch:
  - arm64
startup: application
boot: auto
map:
  - config:rw
image: ghcr.io/ecokeley/home-management:1.0
host_dbus: true
devices:
  - /dev/dri:/dev/dri
environment:
  DISPLAY: ":0"